# Generated by Django 5.2 on 2025-04-28 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MenuItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Название пункта"),
                ),
                (
                    "menu_name",
                    models.CharField(max_length=100, verbose_name="Название меню"),
                ),
                (
                    "url",
                    models.CharField(max_length=255, verbose_name="URL или named URL"),
                ),
                ("position", models.IntegerField(default=0, verbose_name="Позиция")),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="tree_menu.menuitem",
                        verbose_name="Родительский пункт",
                    ),
                ),
            ],
            options={
                "verbose_name": "Пункт меню",
                "verbose_name_plural": "Пункты меню",
                "ordering": ["position"],
            },
        ),
    ]
